"""Daily activities and lifestyle questions."""

ACTIVITY_QUESTIONS = [
    {
        "id": "act_1",
        "question": "What does your typical morning routine look like?",
        "type": "single_choice",
        "options": [
            "Structured routine (exercise, breakfast, plan the day)",
            "Quick and efficient (get ready, out the door)",
            "Slow and mindful (meditation, journaling, gradual start)",
            "Chaotic (hit snooze multiple times, rush)",
            "No routine — every day is different",
        ],
        "traits": {
            "Structured routine (exercise, breakfast, plan the day)": {"discipline": 5, "planning": 5, "health_consciousness": 4},
            "Quick and efficient (get ready, out the door)": {"efficiency_focus": 5, "pragmatism": 4},
            "Slow and mindful (meditation, journaling, gradual start)": {"mindfulness": 5, "self_care": 5, "emotional_intelligence": 4},
            "Chaotic (hit snooze multiple times, rush)": {"spontaneity": 3, "low_discipline": 4, "night_owl": 4},
            "No routine — every day is different": {"flexibility": 5, "spontaneity": 5, "adaptability": 4},
        },
    },
    {
        "id": "act_2",
        "question": "How do you prefer to spend your free time?",
        "type": "multi_choice",
        "options": [
            "Reading or learning something new",
            "Physical exercise or sports",
            "Socializing with friends/family",
            "Creative hobbies (art, music, writing)",
            "Gaming or entertainment",
            "Outdoor activities (hiking, gardening)",
            "Volunteering or community service",
            "Relaxing and doing nothing",
        ],
        "traits": {
            "Reading or learning something new": {"intellectual_curiosity": 5, "growth_mindset": 5},
            "Physical exercise or sports": {"health_consciousness": 5, "energy_level": 5, "discipline": 4},
            "Socializing with friends/family": {"social_orientation": 5, "relationship_focus": 5, "extraversion": 4},
            "Creative hobbies (art, music, writing)": {"creativity": 5, "self_expression": 5, "emotional_depth": 4},
            "Gaming or entertainment": {"relaxation_need": 4, "tech_comfort": 4},
            "Outdoor activities (hiking, gardening)": {"nature_connection": 5, "physical_activity": 4, "mindfulness": 3},
            "Volunteering or community service": {"empathy": 5, "altruism": 5, "community_orientation": 5},
            "Relaxing and doing nothing": {"self_care": 4, "comfort_seeking": 4},
        },
    },
    {
        "id": "act_3",
        "question": "How many hours of screen time (non-work) do you average daily?",
        "type": "single_choice",
        "options": [
            "Less than 1 hour",
            "1-2 hours",
            "3-4 hours",
            "5-6 hours",
            "More than 6 hours",
        ],
        "traits": {
            "Less than 1 hour": {"digital_detachment": 5, "outdoor_preference": 4, "discipline": 4},
            "1-2 hours": {"balance_seeking": 5, "moderation": 4},
            "3-4 hours": {"digital_comfort": 3, "average_engagement": 3},
            "5-6 hours": {"digital_comfort": 4, "sedentary_tendency": 3},
            "More than 6 hours": {"digital_dependency": 4, "sedentary_tendency": 4},
        },
    },
    {
        "id": "act_4",
        "question": "How do you handle your daily to-do list?",
        "type": "single_choice",
        "options": [
            "Written list with priorities — I check items off",
            "Mental list — I keep track in my head",
            "Digital tools and apps",
            "I go with the flow — no list needed",
            "I make lists but rarely follow them",
        ],
        "traits": {
            "Written list with priorities — I check items off": {"organization": 5, "discipline": 5, "planning": 5},
            "Mental list — I keep track in my head": {"confidence": 4, "cognitive_ability": 4},
            "Digital tools and apps": {"tech_reliance": 5, "organization": 4, "efficiency_focus": 4},
            "I go with the flow — no list needed": {"spontaneity": 5, "flexibility": 5, "easygoing": 5},
            "I make lists but rarely follow them": {"aspiration": 4, "execution_gap": 4, "self_awareness": 3},
        },
    },
    {
        "id": "act_5",
        "question": "What time of day do you feel most productive?",
        "type": "single_choice",
        "options": [
            "Early morning (5-8 AM)",
            "Late morning (9-11 AM)",
            "Afternoon (12-4 PM)",
            "Evening (5-8 PM)",
            "Night (after 9 PM)",
        ],
        "traits": {
            "Early morning (5-8 AM)": {"discipline": 5, "morning_person": 5, "proactivity": 5},
            "Late morning (9-11 AM)": {"balance_seeking": 4, "moderate_rhythm": 4},
            "Afternoon (12-4 PM)": {"steady_rhythm": 4, "social_synchrony": 3},
            "Evening (5-8 PM)": {"reflective": 3, "evening_oriented": 4},
            "Night (after 9 PM)": {"creativity": 4, "night_owl": 5, "unconventional": 4},
        },
    },
]
